apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: conectcar
  description: Place to test integration with backstage.io
  labels:
    example.com/custom: conectcar
  annotations:
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - c_sharp
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: squad_backoffice
  system: public-websites
