apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cliente-v3
  description: Representa as funcionalidades de gestão core de clientes.
  labels:
    resource-type: webapp
    language-framework: netcore5.1
    appinsights-name: ConectCarApis
    appinsights-rolename: ClienteV3
  tags:
    - csharp
    - netcore32
    - webapp
  links:
    - url: https://qa-wa-cadastroclientebackendapiv3.azurewebsites.net/swagger/index.html
      title: Swagger
      icon: api
      type: swagger
  annotations:
    github.com/project-slug: andersonaskm/conectcar
spec:
  type: service
  lifecycle: deprecated
  owner: squad-varejo
  system: apicore
  dependsOn: ['resource:cosmos-cliente', 'resource:cosmos-endereco']
